### PR TITLE
DSS_Python 0.10.5, API sync and better error handling

### LINKED ISSUE #42: Daily is not present in PVSystems.
I noticed `dss.PVSystem.Daily` is not available to add an irradiance time series to a PV system. Can this be made available to enable time simulations including solar panels?

### LINKED ISSUE #83: update dss_python version from requirements
### Versions

- [3.8.2] Python version: 
- [x86] Python architecture: 
- [Windows 10 pro  1909 build 18363.900 ] Operating system and version: 
- [ ] OpenDSSDirect.py version number: 

### Feature Request
Update the required version of dss_python, or the verification to greater than instead of equal.
The current required version of dss_python (0.10.1) is not available in pip (the available versions are 0.10.4 and 0.10.5).

image

### PR DESCRIPTION
**Pull request by PMeira**
Upgrade do DSS_Python 0.10.5, synchronizing the API (still maintain ODD.py's conventions):
- Add previously missing modules (API extensions)
- Add CheckForError for most setters
- Update many docstrings
- Introduce many new functions/properties, either new functions from DSS C-API or functions ported from the official COM module API
- Remove some functions with side-effects from `_columns`

Closes #42, closes #83, potentially #69 as well (needs test).

Remaining tasks:
- [x] Update tests after the API sync

### CODE REVIEW

**Comment by PMeira** [comment]
Tests passing in dss_python, odd.jl and here in odd.py. I'll try to release tomorrow to allow us to merge this.

Like I mentioned in #75 and dss-extensions/dss_capi#74, the new components were added to the base engine but they're kinda buggy still (even on the official OpenDSS).

**Comment by PMeira** [comment]
@kdheepak I think this is good to go if the CI tests pass OK. 

I started adding missing functions, which are mostly many DSS C-API extensions and a couple of new functions ported from the COM API, but I decided to skip those in this PR and approach them more automatically.

I started writing a basic transformation to port the useful code from dss_python to oddpy, akin to what I did in the initial dss_capi migration but directly on the Python code this time. I'm planning on doing this on 2 steps:

- Use that to add the missing functions and the basic error-to-exception translation. This should also address issues #42 and #69. We could make a release here.
- Generate most of the code in the form discussed in #55.

This will help keep the implementations in sync (in terms of new dss_capi functions) and reduce (manual) coding errors.

**Comment by PMeira** [comment]
> I started writing a basic transformation to port the useful code from dss_python to oddpy, akin to what I did in the initial dss_capi migration but directly on the Python code this time. I'm planning on doing this on 2 steps:
> - Use that to add the missing functions and the basic error-to-exception translation. This should also address issues #42 and #69. We could make a release here.

I was able to finish this, but still need to update the tests again after the changes. Some are failing due to previous misuse, some just because I changed the available `_columns` for the dataframes.

**Comment by kdheepak** [comment]
This is great! 

```
odd.Circuit.Variable(MyVarName, Code) -> odd.Circuit.Variable(MyVarName)
odd.Circuit.Variablei(Idx, Code) -> odd.Circuit.Variablei(Idx)
```

Technically this is breaking. I think these are the only two functions though. We could add a `Code=None` in the function definition and add a deprecation warning that triggers if `Code is not None` in the function body. And in the next version we can make the change as in this PR.

Also, this PR will now cause functions to error (as it should) where as previously if something went wrong it would be silent and return. I would not expect that from `v0.3.7` to `v0.3.8` of a package to cause this, even if it the correct thing to do and even if I would prefer it. Thoughts?

Maybe we can just update to `v0.4.0` before tagging?

**Comment by PMeira** [comment]
> ```
> odd.Circuit.Variable(MyVarName, Code) -> odd.Circuit.Variable(MyVarName)
> odd.Circuit.Variablei(Idx, Code) -> odd.Circuit.Variablei(Idx)
> ```
> 
> Technically this is breaking. I think these are the only two functions though. We could add a `Code=None` in the function definition and add a deprecation warning that triggers if `Code is not None` in the function body. And in the next version we can make the change as in this PR.
> 

That's a good idea. I can enable the test for that too.

> Maybe we can just update to `v0.4.0` before tagging?

Yes, incrementing just the micro version could be misleading. Since there are a bunch of new functions and modules, I think jumping to v0.4.0 is fine. 

After #55, we may need to do it again, depending on how it ends up looking.

I will try to work on updating the tests tonight. Soon after that, I'll start another branch/PR about the class-based version and iterators. It should be a relatively quick change but certainly will require at least some new tests to ensure it's working as expected and mostly compatible with the current version. 

We probably can wait a few more days and then announce the resulting version on the official forums to reach more users. I noticed more and more users of ODD.py posting there.

**Comment by PMeira** [comment]
The latest push fixed the CI configs to use the main PyPI instead of the test instance (test.pypi.org) when installing dss_python. I'll upload the pre-releases to the main instance next time to avoid this kind of change.

**Comment by PMeira** [comment]
@kdheepak Do you mind if I merge this one and prepare a release on the weekend?

**Comment by kdheepak** [comment]
I think it looks good! Sorry for the delayed responses.

**Pull request merged**
